apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator-ui
  namespace: postgres
spec:
  chart:
    spec:
      chart: postgres-operator-ui
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-ui
        namespace: flux-system
  interval: 24h
  values:
