kind: ConfigMap
apiVersion: v1
metadata:
  name: sflow-scripts
  namespace: default
data:
  bgp.js: |
    var reflectorIP  = '10.0.0.1';
    var myAS         = '65162';
    var myID         = '2a07:54c7:5201:7e6f::1122';
    var sFlowAgentIP = '10.0.0.1';

    // allow BGP connection from reflectorIP
    bgpAddNeighbor(reflectorIP,myAS,myID);

    // direct sFlow from sFlowAgentIP to reflectorIP routing table
    // calculate a 60 second moving average byte rate for each route
    bgpAddSource(sFlowAgentIP,reflectorIP,60,'bytes');
