apiVersion: v1
kind: Service
metadata:
  name: sflow
  namespace: default
spec:
  selector:
    app: sflow
  type: ClusterIP
  # sessionAffinity: None
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  ports:
    - name: http
      protocol: TCP
      port: 8008
      targetPort: 80
