apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stingalleman.nl
  namespace: default
spec:
  secretName: stingalleman.nl-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.stingalleman.nl"
  dnsNames:
    - "stingalleman.nl"
    - "*.stingalleman.nl"
