apiVersion: v1
kind: Service
metadata:
  name: generic-pooler
  namespace: postgres
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
    io.cilium/lb-ipam-ips: "10.10.201.211"
# spec:
#   ports:
#     - name: generic-pooler
#       protocol: TCP
#       port: 5432
#       targetPort: 5432
#       nodePort: 31669
#   selector:
#     connection-pooler: generic-pooler
#   clusterIP: 10.98.165.32
#   clusterIPs:
#     - 10.98.165.32
#   type: LoadBalancer
#   sessionAffinity: None
#   loadBalancerSourceRanges:
#     - 10.10.11.2/32
#     - 87.208.225.224/32
#   externalTrafficPolicy: Cluster
#   ipFamilies:
#     - IPv4
#   ipFamilyPolicy: SingleStack
#   allocateLoadBalancerNodePorts: true
#   internalTrafficPolicy: Cluster
