apiVersion: v1
kind: Service
metadata:
  name: matrix
  namespace: matrix
spec:
  selector:
    app: matrix
  type: ClusterIP
  # sessionAffinity: None
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  ports:
    - name: synapse
      protocol: TCP
      port: 8008
      targetPort: 8008
