apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-data
  namespace: matrix
  labels:
    app: matrix
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
