apiVersion: apps/v1
kind: Deployment
metadata:
  name: yucky-rs
  namespace: discord-bots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yucky-rs
  template:
    metadata:
      labels:
        app: yucky-rs
    spec:
      containers:
        - name: yucky-rs
          image: ghcr.io/dev-shit/yucky.rs:main
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: yucky-rs
                  key: database_url
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yucky-rs
                  key: discord_token
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Prague
            type: File
