apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
  namespace: default
  labels:
    app: pgadmin4
spec:
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      containers:
        - name: dpage
          image: pgadmin4:latest
          ports:
            - containerPort: 5050
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
