apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: timescaledb-single
  namespace: timescaledb
spec:
  chart:
    spec:
      chart: timescaledb-single
      sourceRef:
        kind: HelmRepository
        name: timescaledb
        namespace: flux-system
      # version: "10.33.0"
  interval: 24h
  # values:
