apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  interval: 5m
  values:
    replicaCount: 2
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi

    # Kubernetes Service settings
    service:
      enabled: true
      annotations:
        metallb.universe.tf/address-pool: external
      type: LoadBalancer
      metricsPort: 9797
      httpPort: 9898
      externalPort: 9898
      grpcPort: 9999
      grpcService: podinfo
      nodePort: 31198
      # the port used to bind the http port to the host
      # NOTE: requires privileged container with NET_BIND_SERVICE capability -- this is useful for testing
      # in local clusters such as kind without port forwarding
      hostPort:
