apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami.yaml
  - jetstack.yaml
  - k8s-at-home.yaml
  - metallb.yaml
  - coredns.yaml
  - nfs-provisioner.yaml
  - ory.yaml
  - podinfo.yaml
  - postgres-operator.yaml
  - prometheus-community.yaml
  - traefik.yaml
