apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-ops-view
  namespace: kube-ops-view
spec:
  chart:
    spec:
      chart: kube-ops-view
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
  interval: 5m
    # values.yml