apiVersion: v1
kind: Service
metadata:
  name: stingalleman-website
  namespace: default
spec:
  selector:
    app: stingalleman-website
  type: ClusterIP
  # sessionAffinity:
  ports:
    - name: stingalleman-website
      protocol: TCP
      port: 80
      targetPort: 80
