apiVersion: v1
kind: Service
metadata:
  name: mail-smtp
  namespace: ory
  labels:
    app.kubernetes.io/name: fake-smtp-server
spec:
  type: LoadBalancer
  ports:
    - port: 1025
      targetPort: smtp
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fake-smtp-server
