apiVersion: v1
kind: Service
metadata:
  name: fake-smtp-server-ui
  namespace: ory
  labels:
    app.kubernetes.io/name: fake-smtp-server
spec:
  type: ClusterIP
  ports:
    - port: 4436
      targetPort: http-mail-ui
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fake-smtp-server
