apiVersion: apps/v1
kind: Deployment
metadata:
  name: krill
  namespace: default
  labels:
    app: krill
spec:
  selector:
    matchLabels:
      app: krill
  replicas: 1
  template:
    metadata:
      labels:
        app: krill
    spec:
      containers:
        - name: krill
          image: nlnetlabs/krill
          # command: ["sh", "-c", "sleep 84000s"]
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          # livenessProbe:
          #   tcpSocket:
          #     port: 80
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /_status/healthz
          #     port: 80
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 2
          #   successThreshold: 1
          #   failureThreshold: 3
          #   periodSeconds: 10
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: KRILL_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: krill-auth-token
                  key: token
            - name: KRILL_FQDN
              value: "rpki.as216455.net"
            - name: KRILL_LOG_LEVEL
              value: debug
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: krill-data
              mountPath: /var/krill/data
      volumes:
        - name: krill-data
          persistentVolumeClaim:
            claimName: krill-data
      restartPolicy: Always
