apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: krill-data
  namespace: default
  labels:
    app: krill
spec:
  storageClassName: nfs-client
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 5G
