apiVersion: v1
kind: Service
metadata:
  # annotations:
  # external-dns.alpha.kubernetes.io/hostname: generic-pooler.postgres.db.example.com
  # annotations:
  # io.cilium/lb-ipam-ips: "10.10.102.204"
  # ,2a07:54c7:5201:6e6f::a"
  name: generic-pooler
  namespace: postgres

spec:
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: PreferDualStack
  # loadBalancerSourceRanges:
  #   - 10.10.11.2/32
  #   - 87.208.225.224/32
  ports:
    - name: generic-pooler
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    connection-pooler: generic-pooler
  # sessionAffinity: None
  type: LoadBalancer
