apiVersion: v1
kind: Service
metadata:
  name: irc-lb
  namespace: default
  # annotations:
  #   io.cilium/lb-ipam-ips: "45.83.205.8,2a07:54c7:5201:6e6f::a"
  #   cilium/lb-ipam-sharing-key: "lb1"
  # labels:
  #   lb-pool: external
spec:
  selector:
    app: irc
  type: LoadBalancer
  # ipFamilies:
  #   - IPv4
  #   - IPv6
  # ipFamilyPolicy: RequireDualStack
  ports:
    - name: irc-tls
      port: 6697
      targetPort: 6697
    - name: irc
      port: 6667
      targetPort: 6667
