---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: upgradeScheme
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: upgradeSchemeTemp
spec:
  redirectScheme:
    scheme: https
    permanent: false