---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: upgradeScheme
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: upgradeSchemeTemp
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: false