apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-ingress
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version:  10.19.4
  interval: 5m
  values:
    globalArguments:
      - "--global.checknewversion"
      - "--global.sendanonymoususage"
      - "--api"
      - "--api.insecure"
      - "--certificatesresolvers.le-resolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le-resolver.acme.storage=/certs/acme.json"
      # - "--providers.kubernetesingress"

    persistence:
      enabled: true
      path: /certs
      size: 128Mi
    #
    # Configure providers
    #
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: false
        # ingressClass: traefik-internal
        # labelSelector: environment=production,method=traefik

      kubernetesIngress:
        enabled: true
        allowExternalNameServices: false
        allowEmptyServices: true
        ingressClass: traefik
        # labelSelector: environment=production,method=traefik
        # IP used for Kubernetes Ingress endpoints
        publishedService:
          enabled: false
          # Published Kubernetes Service to copy status from. Format: namespace/servicename
          # By default this Traefik service
          # pathOverride: ""