# All resources definition must be declared
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: routes
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`test12345.stingalleman.nl`)
      priority: 10
      middlewares:
        - name: upgrade-scheme
          namespace: default
      services:
        - kind: Service
          name: website
          namespace: default
          passHostHeader: true
          port: 80
