apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: irc-db
  labels:
    app: irc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
