---
- name: "Set VyOS VLAN"
  hosts: vyos
  connection: network_cli
  serial: 1
  vars:
    vlan: 200
    vlan_description: "test!"
    vlan_interface: "eth2"
    site: "AMS"
    tenant: "System"
    vlan_address: "10.10.{{ vlan }}.0/24"
    vlan_address6: "2a05:dfc1:8502:{{ vlan }}::1/64"
    vlan_name: "V{{ vlan }}"

  tasks:
    - name: "Create vlan {{ vlan }}"
      vyos.vyos.vyos_vlan:
        vlan_id: "{{ vlan }}"
        name: "{{ vlan_name }}"
        interfaces:
          - "{{ vlan_interface }}"
        address: "{{ vlan_address }}"

    - name: "Set firewalls on interfaces"
      vyos.vyos.vyos_config:
        lines:
          - set interface ethernet {{ vlan_interface }} vif {{ vlan }} address {{ vlan_address6 }}
          - set interface ethernet {{ vlan_interface }} vif {{ vlan }} firewall in name VLAN-VLAN
          - set interface ethernet {{ vlan_interface }} vif {{ vlan }} firewall out name VLAN-VLAN
          - set interface ethernet {{ vlan_interface }} vif {{ vlan }} firewall local name VLAN-VLAN
          - set interface ethernet {{ vlan_interface }} vif {{ vlan }} firewall in ipv6-name VLAN-VLAN6
          - set interface ethernet {{ vlan_interface }} vif {{ vlan }} firewall out ipv6-name VLAN-VLAN6
          - set interface ethernet {{ vlan_interface }} vif {{ vlan }} firewall local ipv6-name VLAN-VLAN6

    - name: "Set firewall rules"
      vyos.vyos.vyos_config:
        lines:
          - set firewall name VLAN-VLAN rule {{ vlan }} description "{{ vlan_name }}"
          - set firewall name VLAN-VLAN rule {{ vlan }} source address {{ vlan_address }}
          - set firewall name VLAN-VLAN rule {{ vlan }} destination  address {{ vlan_address }}
          - set firewall name VLAN-VLAN rule {{ vlan }} action accept
          - set firewall ipv6-name VLAN-VLAN6 rule {{ vlan }} description "{{ vlan_name }}"
          - set firewall ipv6-name VLAN-VLAN6 rule {{ vlan }} source address {{ vlan_address }}
          - set firewall ipv6-name VLAN-VLAN6 rule {{ vlan }} destination  address {{ vlan_address }}
          - set firewall ipv6-name VLAN-VLAN6 rule {{ vlan }} action accept

    - name: "Update LAN zone policy"
      vyos.vyos.vyos_config:
        lines:
          - set zone-policy zone LAN interface {{ vvlan_interface }}.{{ vlan }}

    - name: "Set Netbox VLAN"
      netbox.netbox.netbox_vlan:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ vlan_name }}"
          vid: "{{ vlan }}"
          site: "{{ site }}"
          tenant: "{{ tenant }}"
          description: "{{ vlan_description }}"

    - name: "Set Netbox prefix"
      netbox.netbox.netbox_prefix:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          prefix: "{{ vlan_address }}"
          tenant: "{{ tenant }}"
          site: "{{ site }}"
          description: "{{ vlan_description }}, {{ vlan_name }}"

    - name: "Set Netbox prefix (V6)"
      netbox.netbox.netbox_prefix:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          prefix: "{{ vlan_address6 }}"
          tenant: "{{ tenant }}"
          site: "{{ site }}"
          description: "{{ vlan_description }}, {{ vlan_name }} (V6)"
