kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "acid-tweede-kamer"
  namespace: "default"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "14"
  numberOfInstances: 1
  enableMasterLoadBalancer: true
  enableReplicaLoadBalancer: true
  enableConnectionPooler: true
  volume:
    size: "10Gi"
  users:
    tk-sync: []
  databases:
    tweedekamer: tk-sync
  allowedSourceRanges:
    # IP ranges to access your cluster go here

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
