apiVersion: v1
kind: Service
metadata:
  name: supertuxkart
  namespace: default
  annotations:
    metallb.universe.tf/address-pool: external
spec:
  loadBalancerIP: "45.83.205.10"
  ports:
    - port: 2759
      targetPort: 2759
      # protocol: UDP
      name: port1
    - port: 2757
      targetPort: 2757
      protocol: UDP
      # name: port2
  selector:
    app: supertuxkart
  type: LoadBalancer
