apiVersion: v1
kind: Service
metadata:
  name: pdns-admin
  namespace: default
spec:
  selector:
    app: pdns-admin
  type: ClusterIP
  # sessionAffinity:
  ports:
    - name: pdns-admin
      protocol: TCP
      port: 9191
      targetPort: 9191
