apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: nfs-provisioner
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
        namespace: flux-system
  interval: 24h
  values:
    nfs:
      server: "10.10.10.20"
      path: "/media/nfs/k8s"
    storageClass:
      defaultClass: true
