apiVersion: apps/v1
kind: Deployment
metadata:
  name:  stingalleman.nl
  namespace: default
  labels:
    app:  stingalleman.nl
spec:
  selector:
    matchLabels:
      app: stingalleman.nl
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  stingalleman.nl
    spec:
      containers:
      - name:  stingalleman.nl
        image:  stingalleman/stingalleman.nl
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  80
          name:  http_web
      restartPolicy: Always