apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mattermost
  namespace: default
spec:
  chart:
    spec:
      chart: mattermost-team-edition
      sourceRef:
        kind: HelmRepository
        name: mattermost
        namespace: flux-system
      version: "6.6.51"
  interval: 24h
  valuesFrom:
    - kind: ConfigMap
      name: mattermost-values
      valuesKey: data
