apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cluster.boem
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`alerts.cluster.boem`)
      services:
        - kind: Service
          name: alertmanager-operated
          namespace: monitoring
          passHostHeader: true
          port: 9093

    - kind: Rule
      match: Host(`traefik.cluster.boem`)
      services:
        - name: traefik-api
          namespace: traefik
          port: 9000

    - kind: Rule
      match: Host(`longhorn.cluster.boem`)
      services:
        - name: longhorn-frontend
          namespace: longhorn-system
          port: 80

    - kind: Rule
      match: Host(`prometheus.cluster.boem`)
      services:
        - name: prometheus-operated
          namespace: monitoring
          port: http-web

    - kind: Rule
      match: Host(`postgres.cluster.boem`)
      services:
        - name: postgres-operator-ui
          namespace: postgres
          port: 80

    - kind: Rule
      match: Host(`mailslurper.cluster.boem`)
      services:
        - name: fake-smtp-server-ui
          namespace: ory
          port: 4436

    - kind: Rule
      match: Host(`mailslurper.cluster.boem`) && PathPrefix(`/admin`)
      services:
        - name: fake-smtp-server-admin
          namespace: ory
          port: 4437

  tls:
    secretName: cluster.boem-certs
