apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: dns-udp
  namespace: default
spec:
  entryPoints:
    - dns-udp
  routes:
    - services: # [3]
        - name: coredns-external-coredns # [4]
          port: 53 # [5]
          weight: 10 # [6]
    # - kind: Rule
    #   match: Host(`ns1.stingalleman.dev`)
    #   services:
    #     - name: coredns-external-coredns
    #       namespace: dns
    #       port: 53

    # - kind: Rule
    #   match: Host(`ns2.stingalleman.dev`)
    #   services:
    #     - name: coredns-external-coredns
    #       namespace: dns
    #       port: 53
