apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: stingalleman.dev
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`discord.stingalleman.dev`)
      services:
        - kind: Service
          name: coc-bot
          namespace: discord-bots
          passHostHeader: true
          port: 8020

    - kind: Rule
      match: Host(`kratos.stingalleman.dev`)
      services:
        - name: kratos-public
          namespace: ory
          port: 80

    - kind: Rule
      match: Host(`admin.kratos.stingalleman.dev`)
      services:
        - name: kratos-admin
          namespace: ory
          port: 80

    - kind: Rule
      match: Host(`selfservice.kratos.stingalleman.dev`)
      services:
        - name: selfservice
          namespace: ory
          port: 3000

  tls:
    certResolver: dns-resolver
