apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxidized
  namespace: oxidized
  labels:
    app: oxidized
spec:
  selector:
    matchLabels:
      app: oxidized
  replicas: 1
  template:
    metadata:
      labels:
        app: oxidized
    spec:
      containers:
        - name: oxidized
          image: oxidized/oxidized
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 8888
              name: oxidized
          volumeMounts:
            - name: oxidized
              mountPath: "/root/.config/oxidized"
              readOnly: true
            - name: oxidized-storage
              mountPath: "/etc/oxidized-storage"
          env:
            - name: OXIDIZED_LOGS
              value: /etc/oxidized-storage/logs
      volumes:
        - name: oxidized
          secret:
            secretName: oxidized
        - name: oxidized-storage
          persistentVolumeClaim:
            claimName: oxidized-storage
      restartPolicy: Always