apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oxidized-storage
  namespace: oxidized
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Mi