apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oxidized-logs
  namespace: oxidized
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mib