apiVersion: v1
kind: Service
metadata:
  name: sflow-rt-sflow
  namespace: default
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  selector:
    name: sflow-rt
  ports:
    - protocol: UDP
      port: 6343
---
apiVersion: v1
kind: Service
metadata:
  name: sflow-rt-rest
  namespace: default
spec:
  type: ClusterIP
  selector:
    name: sflow-rt
  ports:
    - protocol: TCP
      port: 8008
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sflow-rt
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sflow-rt
  template:
    metadata:
      labels:
        name: sflow-rt
    spec:
      containers:
        - name: sflow-rt
          image: sflow/prometheus:latest
          ports:
            - name: http
              protocol: TCP
              containerPort: 8008
            - name: sflow
              protocol: UDP
              containerPort: 6343
