apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: internal-whitelist
  namespace: default
spec:
  ipWhiteList:
    sourceRange:
      - 10.10.11.11/32
      - 10.10.11.2/32
      - 10.10.11.9/32
      - 87.208.225.224/32
