apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: maishond.nl
  namespace: default
spec:
  secretName: maishond.nl-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.maishond.nl"
  dnsNames:
    - "maishond.nl"
    - "*.maishond.nl"
