# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: monitoring-stack
#   namespace: monitoring
# spec:
#   install:
#     # disableWait: true
#     crds: CreateReplace
#   upgrade:
#     # disableWait: true
#     crds: CreateReplace
#   chart:
#     spec:
#       version: 55.8.1
#       chart: kube-prometheus-stack
#       sourceRef:
#         kind: HelmRepository
#         name: prometheus-community
#         namespace: flux-system
#   interval: 24h
#   values:
#     prometheus:
#       prometheusSpec:
#         storageSpec:
#           volumeClaimTemplate:
#             spec:
#               storageClassName: nfs-client
#               accessModes: ["ReadWriteMany"]
#               resources:
#                 requests:
#                   storage: 20Gi
