apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring-stack
  namespace: monitoring
spec:
  install:
    # disableWait: true
    crds: CreateReplace
  upgrade:
    # disableWait: true
    crds: CreateReplace
  chart:
    spec:
      version: 55.8.1
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 24h
  values:
    prometheus:
      prometheusSpec:
        additionalScrapeConfigs:
          - job_name: "sflow-rt-analyzer"
            metrics_path: /prometheus/analyzer/txt
            static_configs:
              - targets: ["https://sflow.kluster.boem"]
          - job_name: "sflow-rt-metrics"
            metrics_path: /prometheus/metrics/ALL/ALL/txt
            static_configs:
              - targets: ["https://sflow.kluster.boem"]
          - job_name: "sflow-rt-flow-src-dst-bps"
            metrics_path: /app/prometheus/scripts/export.js/flows/ALL/txt
            static_configs:
              - targets: ["https://sflow.kluster.boem"]
            params:
              metric: ["ip_src_dst_bps"]
              key: ["ipsource", "ipdestination"]
              label: ["src", "dst"]
              value: ["bytes"]
              scale: ["8"]
              minValue: ["1000"]
              maxFlows: ["100"]

        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-client
              accessModes: ["ReadWriteMany"]
              resources:
                requests:
                  storage: 20Gi
