apiVersion: v1
kind: Service
metadata:
  name: actual-budget-service-emiel
  namespace: actual-budget
spec:
  selector:
    app: actual-budget-emiel
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5006
      targetPort: 5006
