apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget-volume-emiel
  namespace: actual-budget
  labels:
    app: actual-budget-emiel
spec:
  # storageClassName:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
