# apiVersion: v1
# kind: Service
# metadata:
#   name: sting-as-site
#   namespace: default
# spec:
#   selector:
#     app: sting-as-site
#   type: ClusterIP
#   sessionAffinity: None
#   sessionAffinityConfig:
#     clientIP:
#       timeoutSeconds: 10800
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 80

apiVersion: v1
kind: Service
metadata:
  name: sting-as-site
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.10.102.205
spec:
  selector:
    app: sting-as-site
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
