apiVersion: v1
kind: Service
metadata:
  name: sting-as-site
  namespace: default
  annotations:
    io.cilium/lb-ipam-ips: "45.83.205.8"
spec:
  selector:
    app: sting-as-site
  type: LoadBalancer
  # sessionAffinity: None
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
