apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "cilium-lb-pool-external"
spec:
  allowFirstLastIPs: Yes
  blocks:
    - cidr: "10.10.102.224/29"
    - cidr: "45.83.205.8/32"
    # - start: "45.83.205.8"
    #   stop: "45.83.205.9"
    # - cidr: "2a07:54c7:5201:6e6f::/64"
