apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "cilium-lb-pool-external"
spec:
  allowFirstLastIPs: Yes
  blocks:
    - start: "10.10.102.200"
      stop: "10.10.102.250"
    - cidr: "45.83.205.8/32"
    - cidr: "2a07:54c7:5201:6e6f::/64"
