apiVersion: v1
kind: Service
metadata:
  name: hubble-relay-ext
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4245
  selector:
    k8s-app: hubble-relay
  type: LoadBalancer
  # internalTrafficPolicy: Cluster
